### ISSUE TITLE
The `deepset` dir must created by manually

### ISSUE THREAD

**Issue by linkerlin** [nlpodyssey/spago#112]
In the ~/.spago dir:
There is no deepset , if we do not create it for  the huggingface-importer.

**Comment by linkerlin** [comment]
And the `~/.spago/deepset/bert-base-cased-squad2/`

**Comment by linkerlin** [comment]
spago make a dir named `~` in the spago source code dir, not in the home-dir.

**Comment by linkerlin** [comment]
more `homedir.Expand()` need to convert path `~` to HomeDir

**Comment by matteo-grella** [comment]
@linkerlin please checkout [Cybertron](https://github.com/nlpodyssey/cybertron) as all the NLP functionality have been moved there :)
