### ISSUE TITLE
flair models no longer work

### ISSUE THREAD

**Issue by akhudek** [nlpodyssey/spago#113]
In particular, running this example:

https://github.com/nlpodyssey/spago-examples/tree/main/examples/named_entities_recognition

with the provided example model and sentence produces nonsense tags.

My go version is:
go version go1.18.1 darwin/arm64

**Comment by matteo-grella** [comment]
Hi @akhudek 

Could you try compiling with `GOARCH=amd64` and let me know?

**Comment by akhudek** [comment]
Yep, that works. So it's an M1 target that causes it. Thanks.
