### ISSUE TITLE
how to convert hf models to spago format?

### ISSUE THREAD

**Issue by JackKCWong** [nlpodyssey/spago#116]
Apologies if this is a silly question. But it seems there used to be an importor for huggingface models but it disappeared from the main branch / readme.
There are binary available elsewhere but I just want to make sure I am using the official and latest approach.

**Comment by matteo-grella** [comment]
Currently, the main branch contains version v1, which differs substantially from version [v0.7](https://github.com/nlpodyssey/spago/tree/v0.7.0). For NLP-related features, including Hugging Face Hub models converter, check out the [Cybertron](https://github.com/nlpodyssey/cybertron) package!

**Comment by JackKCWong** [comment]
thanks!
