### ISSUE TITLE
Support HTTPS by default

### ISSUE THREAD

**Issue by evanmcclure** [nlpodyssey/spago#19]
Support HTTPS by default, to maintain best practices in delivering cloud-native applications.

**Comment by evanmcclure** [comment]
Here is a list of flags I propose adding to the servers in order to support TLS.

`-address` - changes the bind address. The default is "0.0.0.0:1987".
`-tls-disable` - specifies that TLS is disabled. TLS is enabled by default.
`-tls-cert-file` - specifies the path of the TLS certificate file. A custom CA certificate may be used by concatenating it to the primary certificate. The default path will be the system cert paths + "/spago-server.crt".
`-tls-key-file` - specifies the path to private key for the certificate. The default path will be the system cert paths + "/spago-server.key".
`-tls-min-version` - changes the minimum supported version of TLS. The default is "tls12".

The command `docker build` will generate a key and self-signed certificate by default.

**Comment by matteo-grella** [comment]
@evanmcclure, I'm all for it!

Before making a pull request, would you like to rebase on the `main`? The server has been slightly changed here #21.

**Comment by evanmcclure** [comment]
👍
