### ISSUE TITLE
Go.mod inside cmd sub-packages?

### ISSUE THREAD

**Issue by matteo-grella** [nlpodyssey/spago#24]
Pull-request #22 introduced something I wasn't aware of. What are the pros and cons to have a dedicated `go.mod` inside a cmd sub-package, like [here](https://github.com/nlpodyssey/spago/blob/main/cmd/huggingfaceimporter/)?

In my understanding, this is a good way to avoid adding global dependencies that are actually only required in `cmd`. Cons?

@paralin

**Comment by paralin** [comment]
That was my motivation to putting it there, to keep the cli packages out of the global deps.

However... We could move the CLI arguments to a package `spago/cli` and remove the extra `go.mod` and just allow the CLI packages to be part of the package deps, I don't think there's much of a downside.
