### ISSUE TITLE
Recommendations for CLI sub-commands

### ISSUE THREAD

**Issue by paralin** [nlpodyssey/spago#25]
Here are some commands that could be in an "auto-demo" cli:

 - importer: the existing downloader we have now
 - answer: question/answer demo, imports a model + runs the demo interactively or with cli flags for the question and passage.
 - more optionally interactive "run it one off" commands

Thoughts?

**Comment by evanmcclure** [comment]
Interesting.

I’ve seen auto demos used by sales engineers.

I’ve never used one in my own explorations. Instead, as a developer, I found that exploring the commands and learning about their interactions in an unopinionated way made more sense to me. 

I love the idea of combining all of the demo programs into one program that uses sub commands, though.

**Comment by paralin** [comment]
Closing for now
