### ISSUE TITLE
Implement gRPC as an alternative to HTTP API

### ISSUE THREAD

**Issue by evanmcclure** [nlpodyssey/spago#35]

**Comment by evanmcclure** [comment]
To keep things simple, we'll use a new port for gRPC, and we'll add a new flag to change the bind-address. The flag will be called `--grpc-address`, and the default value will be "0.0.0.0:1976".

This necessarily implies that there will be two separate handlers for every API, but they will invoke the same API function.

**Comment by matteo-grella** [comment]
Yeah, I agree.
