### ISSUE TITLE
Other integration / Telegram Bot

### ISSUE THREAD

**Issue by x0rzkov** [nlpodyssey/spago#46]
Hi guys,

Hope you are all well !

I was looking for some implementation of AI chatbot golang and found your project `spago`.

And, I am developing a multibot for telegram based on go plugins: https://github.com/paper2code/telegram-multibot

So I was wondering how can I integrate `spago` as a QA bot plugin.

Do you have any insights or advices for such integration ?

Thanks in advance.

Cheers,
X

**Comment by matteo-grella** [comment]
Hey @x0rzkov,

The first thing that comes to mind that you could integrate with a minimum of effort, is a search module on some pre-indexed FAQs.

Thanks to the BERT sentence encoding using [Google's LaBSE model](https://ai.googleblog.com/2020/08/language-agnostic-bert-sentence.html), the chatbot would find the right answer both for questions posed in different words from those provided in "canonical form", and even in different languages.

Let me know; if you are interested I can write a short tutorial to include in the Wiki.

**Comment by x0rzkov** [comment]
@matteo-grella thanks for your reply

For sure, I am interested. :-)

How do you train `spago` on specific questions/answers ?

Ps. I already made telegram QA bot for Arxiv.org papers paper2code/telegram-qa-with-arxiv-papers where I ingested the dataset with the help of the haystack framework.

**Comment by matteo-grella** [comment]
@x0rzkov thank you for your patience! 

I am very busy in this period but I will do my best to answer you in the coming days.

Have you meanwhile managed to run spagGO following the [instructions](https://github.com/nlpodyssey/spago/wiki/Demos#question-answering-demo) for the Question&Answering demo?

**Comment by matteo-grella** [comment]
Hey @x0rzkov,

I've made a repository with an example that's close to your question on the occasion of my talk at GopherCon Europe 2021!

You can look at [this](https://github.com/matteo-grella/gophercon-eu-2021) link and ask any additional questions or close this issue if you wish.

**Comment by x0rzkov** [comment]
thanks I ll have a look :-)

**Comment by x0rzkov** [comment]
Have you tried haystack, the python framework, for QA ?

**Comment by matteo-grella** [comment]
Yes, it’s a wonderful framework!
