### ISSUE TITLE
Not very robust update of Mean and StdDev in BatchNorm

### ISSUE THREAD

**Issue by matteo-grella** [nlpodyssey/spago#49]
A second thought about the recent fix of the BatchNorm (#48) raises an interesting question.

It is the first time that it happens that during a forward, the parameters are directly altered (in this case Mean and StdDev):

https://github.com/nlpodyssey/spago/blob/cb6bad4ccf503bdafe0fde13510ba8868e830c3d/pkg/ml/nn/normalization/batchnorm/batchnorm.go#L80

In general, I believe that the `Optimizer` should be the only responsible for updating the parameters. However, here we are not talking about gradients, so the situation is slightly different.

The first thing that comes to mind is to update these values (Mean and StdDev) by saving them inside the `Processor`. A special method is then added to it which has the effect of updating the model parameters. It remains an _ad hoc_ act, but it seems more robust and consistent with the rest.

@jjviana What do you think? Let's discuss here :)

**Comment by jjviana** [comment]
I am trying to think about other layers that could have this kind of need (updating parameters without gradient computation). As far as I can see, BatchNorm is the only layer that actually needs that.
Saving the values inside Processor would just move the place where values are accumulated, without changing the fact these changes are not produced by an optimizer.
If you want to keep the Optimizer abstraction intact, one could think about a special "BatchNormOptimizer" that could be used here. But it would be necessary also to make it possible for different parameters to be optimized by different optimizers (maybe by attaching an optimizer to the parameter itself?). This would change a lot of the mechanics of how optimization currently works... and just for the sake of BatchNorm.
I would say that unless there are other use cases like BatchNorm (maybe 2 or 3 more) it would be an overkill to change the framework like that.

**Comment by matteo-grella** [comment]
I've thought about it a lot and I agree with you: it doesn't make sense to change the general optimization mechanism only for this isolated case.

Please give me one last confirmation, and I will update the `BatchNorm` documentation explaining this peculiarity and referring to this conversation.

**Comment by matteo-grella** [comment]
I am closing this issue as we discussed it in a call.
