### ISSUE TITLE
Chaining convolution+maxpooling layers

### ISSUE THREAD

**Issue by xiorcale** [nlpodyssey/spago#54]
From what I found, one can create a 1-convolution cnn with the `cnn.NewModel` which will look like this:

- convolution
- max pooling
- linear layer

There is also the `convolution.New` function which creates a new convolution. But how should I proceed if I want to create a bigger model by chaining multiple conv and max pooling before adding a linear layer? e.g. :

- conv1
- max pooling
- conv2
- maxpooling
- linear

I was expecting something like:

```
model := stack.New(
    convolution.New(convConfig)
    pooling.NewMax(2, 2)
    convolution.New(convConfig)
    pooling.NewMax(2, 2)
    linear.New(in, out)
    activation.New(outputAct)
)
```

**Comment by matteo-grella** [comment]
Hey @xiorcale,

Thank you very much for opening this issue!

Following your proposal, we now have a [pooling layer](https://github.com/nlpodyssey/spago/blob/main/pkg/ml/nn/pooling/pooling.go).

So we are getting closer to what you expect :) We may even eliminate the [cnn](https://github.com/nlpodyssey/spago/tree/main/pkg/ml/nn/cnn) package soon!

However, to create this CNN model using only `nn.Stack` we may need an additional layer to _merge_ the last max pooling, to pass it to the linear layer.

In detail, I am referring to [this line](https://github.com/nlpodyssey/spago/blob/c0db025f3959e6b77a010c6ee2430ff7d961a0bf/pkg/ml/nn/cnn/cnn.go#L69) that I also report here for convenience:

```go
concatFilters := p.Graph.Concat(p.vectorize(poolingFilters...)...)
```

Perhaps we could add an auxiliary layer within the pooling package that deals with this merge. Something like:

```go
model := stack.New(
    convolution.New(convConfig)
    pooling.NewMax(2, 2)
    convolution.New(convConfig2)
    pooling.NewMax(2, 2)
    pooling.NewMerge()
    linear.New(in, out)
    activation.New(outputAct)
)
```

Any ideas?

**Comment by xiorcale** [comment]
Woah thanks! it looks good.

Regarding the `concatFilters` problem, I'm not sure I would put this functionality in the `pooling` package. It is very common to just have a `flatten` layer on its own (e.g. https://pytorch.org/docs/stable/generated/torch.nn.Flatten.html).

If you choose this approach, I think the final `stack` should look like that:

```go
model := stack.New(
    convolution.New(convConfig)
    pooling.NewMax(2, 2)
    convolution.New(convConfig2)
    pooling.NewMax(2, 2)
    flatten.New()
    linear.New(in, out)
    activation.New(outputAct)
```

With maybe (?) some configuration parameters to give as input of `flatten.New()`, in the way pytorch is doing it.

**Comment by xiorcale** [comment]
Closing it since https://github.com/nlpodyssey/spago/commit/eeefc92f9538d8e8d9fccdca8e43b055b29abefc has been merged. Thanks 🎉
