### ISSUE TITLE
This is the best thing since sliced bread

### ISSUE THREAD

**Issue by go-dockly** [nlpodyssey/spago#55]
Hello I do not have any issue so feel free to close this but I just wanted to say that spago is fantastic.
Love what has been done here in native go!!!
Thank you everybody involved.
FORZA ITALIA

**Comment by matteo-grella** [comment]
Thank you so much for this feedback, I really appreciate it!

How did you get on this repository? 

By the way, if you could mention spaGO on any of your channels or social networks, I'd also appreciate this:)

**Comment by go-dockly** [comment]
Ciao Matteo, I am working on a personal voice assistant in go. I hope to create the first open source cross platform voice agent you can just run on your own CPU without evil corp snopping up all your privacy :) so from time to time I search for golang bert in google to improve my custom feedforward intent classification net and came across this tutorial from [Anthony Corletti](https://www.anthonycorletti.com/post/nlp-with-golang/) which blew my mind and now I am a FAN.

**Comment by go-dockly** [comment]
I shared the love in golang nuts on linkedin ;-)
