### ISSUE TITLE
create first tag for release

### ISSUE THREAD

**Issue by go-dockly** [nlpodyssey/spago#57]
Hi - In order to manage spaGO as a [versioned dependency](https://research.swtch.com/vgo-principles) in my go project it would be appreciated if a first tagged release was made available.

**Comment by marco-nicola** [comment]
Hi, thanks for opening this issue.

That's a very good point. We will soon create a first tagged release `v0.1.0`.

Most of the public API should remain stable in the near future, yet the likelihood of major refactorings is not negligible. For this reason, we'll probably stick to a `0` major version for a while, only bumping new minor versions, even in case of breaking changes (see also [SemVer reference](https://semver.org/#spec-item-4)).

Another comment will follow shortly, as soon as the first tagged release will be available! :relaxed:

**Comment by go-dockly** [comment]
Thank you Marco!

**Comment by matteo-grella** [comment]
Here we go with our first tagged release [v0.1.0](https://github.com/nlpodyssey/spago/releases/tag/v0.1.0)!
