### ISSUE TITLE
Cannot import project as library

### ISSUE THREAD

**Issue by csaade** [nlpodyssey/spago#94]
Hello,

I am trying to import this project as a library by running the command
`go get -u github.com/nlpodyssey/spago`
(as instructed in the readme)

I am getting the following error:
`cannot find package "github.com/dgraph-io/badger/v2"`

Anyone else got this error?

**Comment by matteo-grella** [comment]
Hi @csaade,

Thanks for pointing out this problem. 

It appears that the reference to [badger](https://github.com/dgraph-io/badger/) v2 has changed or removed. Very odd indeed.

In any case, I updated the dependency to version v3 and everything seems to work smoothly now.

Can you please verify and let me know?

**Comment by csaade** [comment]
Hey @matteo-grella,

Thanks for your help - it's working well on my end now! However, I'm still facing some compilation issues in the huggingfaceimporter code mostly. Here are the errors:

`../go/src/github.com/nlpodyssey/spago/cmd/huggingfaceimporter/internal/importer.go:62:17: cannot use cli.StringFlag literal (type cli.StringFlag) as type cli.Flag in slice literal:
	cli.StringFlag does not implement cli.Flag (Apply method has pointer receiver)
../go/src/github.com/nlpodyssey/spago/cmd/huggingfaceimporter/internal/importer.go:66:4: unknown field 'EnvVar' in struct literal of type cli.StringFlag
../go/src/github.com/nlpodyssey/spago/cmd/huggingfaceimporter/internal/importer.go:69:17: cannot use cli.StringFlag literal (type cli.StringFlag) as type cli.Flag in slice literal:
	cli.StringFlag does not implement cli.Flag (Apply method has pointer receiver)
../go/src/github.com/nlpodyssey/spago/cmd/huggingfaceimporter/internal/importer.go:72:4: unknown field 'EnvVar' in struct literal of type cli.StringFlag
../go/src/github.com/nlpodyssey/spago/cmd/huggingfaceimporter/internal/importer.go:76:15: cannot use cli.BoolFlag literal (type cli.BoolFlag) as type cli.Flag in slice literal:
	cli.BoolFlag does not implement cli.Flag (Apply method has pointer receiver)
../go/src/github.com/nlpodyssey/spago/cmd/huggingfaceimporter/internal/importer.go:79:4: unknown field 'EnvVar' in struct literal of type cli.BoolFlag
# github.com/nlpodyssey/spago/cmd/clientutils
../go/src/github.com/nlpodyssey/spago/cmd/clientutils/client.go:24:17: cannot use cli.StringFlag literal (type cli.StringFlag) as type cli.Flag in slice literal:
	cli.StringFlag does not implement cli.Flag (Apply method has pointer receiver)
../go/src/github.com/nlpodyssey/spago/cmd/clientutils/client.go:29:15: cannot use cli.BoolFlag literal (type cli.BoolFlag) as type cli.Flag in slice literal:
	cli.BoolFlag does not implement cli.Flag (Apply method has pointer receiver)
../go/src/github.com/nlpodyssey/spago/cmd/clientutils/client.go:34:17: cannot use cli.StringFlag literal (type cli.StringFlag) as type cli.Flag in slice literal:
	cli.StringFlag does not implement cli.Flag (Apply method has pointer receiver)
`

Am I doing something wrong?

**Comment by matteo-grella** [comment]
I'm not sure. 

You couldn't report here the sequence of operations and commands that led to this error, could you?

**Comment by matteo-grella** [comment]
Solved by updating the module [github.com/urfave/cli](https://github.com/urfave/cli) to v2.
